apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: play-cluster
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
      publicKeyPath: ~/.ssh/id_ed25519.pub
  - name: ng-2
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 100
    ssh:
      publicKeyPath: ~/.ssh/id_ed25519.pub
